### ISSUE TITLE
Error resolving status.mojang.com

### ISSUE THREAD

**Issue by JustBru00** [SparklingComet/java-mojang-api#11]
This appears to be caused by Mojang shutting down the status service.
https://wiki.vg/Mojang_API#API_Status_-_Outdated

I will try and write a PR that removes the status API.

Full stack trace:
```
java.lang.RuntimeException: com.mashape.unirest.http.exceptions.UnirestException: java.net.UnknownHostException: status.mojang.com: No address associated with hostname
        at org.shanerx.mojang.Mojang.getJSONArray(Mojang.java:406) ~[survivalserver-1.3.1.jar:?]
        at org.shanerx.mojang.Mojang.connect(Mojang.java:70) ~[survivalserver-1.3.1.jar:?]
        at net.introvertscove.survivalserver.plugin.utils.UUIDFetcher.init(UUIDFetcher.java:21) ~[survivalserver-1.3.1.jar:?]
        at net.introvertscove.survivalserver.plugin.utils.UUIDFetcher.getLastName(UUIDFetcher.java:164) ~[survivalserver-1.3.1.jar:?]
        at net.introvertscove.survivalserver.plugin.utils.UUIDFetcher$3.run(UUIDFetcher.java:127) ~[survivalserver-1.3.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-327]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-327]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-327]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: com.mashape.unirest.http.exceptions.UnirestException: java.net.UnknownHostException: status.mojang.com: No address associated with hostname
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143) ~[survivalserver-1.3.1.jar:?]
        at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56) ~[survivalserver-1.3.1.jar:?]
        at org.shanerx.mojang.Mojang.getJSONArray(Mojang.java:401) ~[survivalserver-1.3.1.jar:?]
        ... 10 more
Caused by: java.net.UnknownHostException: status.mojang.com: No address associated with hostname
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[?:?]
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[survivalserver-1.3.1.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[survivalserver-1.3.1.jar:?]
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138) ~[survivalserver-1.3.1.jar:?]
        at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56) ~[survivalserver-1.3.1.jar:?]
        at org.shanerx.mojang.Mojang.getJSONArray(Mojang.java:401) ~[survivalserver-1.3.1.jar:?]
        ... 10 more
```

**Comment by SparklingComet** [comment]
Hi there,
Thanks for submitting the PR.
I was aware of the issue with the status API but have been too busy to work on this. I’ll look at the PR ASAP (probably tomorrow or during the weekend).
